spring.application.name=noise-monitoring-classroom

spring.datasource.url=jdbc:mariadb://localhost:3306/noise_monitoring_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=8080